### ISSUE TITLE
Week 8 

### ISSUE THREAD

**Issue by ShihChiangLo** [YutingWuTia/comp-lab-class#1]
Week 8 looks great!

**Comment by cerbveen** [comment]
# Setup
	Great movie!
# Part 1
	All files are well organized and nicely named! However, a middle point between amorphous and crystalline states is required for assignment. In the author's case, the density is 0.95.
# Part 2
	Very organized! Great job!

--Rui Zeng

**Comment by YutingWuTia** [comment]
Thank you for the reminder.
