### ISSUE TITLE
Week 11 Feedback

### ISSUE THREAD

**Issue by triashap5** [YutingWuTia/comp-lab-class#5]
Hey! I was going through your Week 11 work, but I could not find the outputs. Also the .ipynb files did not seem complete. Are you facing any issue with uploading files in github because I could see the tag "failed github push"?

**Comment by YutingWuTia** [comment]
Thanks for reminding me! I’ve repush the assignment. In the Jupyter notebook, you can find the reason why I did not upload the complete assignment. Anyway, I have solved the problem so don’t worry. If you don’t mind could you please review again?

**Comment by triashap5** [comment]
Hey! No problem, I checked your assignment once again. Everything seems pretty good! Well done!!
Also, regarding the 'dead kernel' problem, I faced similar issues to which Glen told me to just remove the last molecule from the .csv file and run the entire code for 9 particles. But it's great that you could resolve the issue. Keep it up!
